export const QUESTION_TITLES: Record<string, string> = {
  smoking: "¿Fumás cigarrillos?",
  marijuana: "¿Fumás marihuana?",
  alcohol: "¿Tomás alcohol?",
  pets: "¿Tenés mascotas?",
  acceptPets: "¿Aceptás mascotas?",
  tidiness: "¿Cuán ordenado/a sos?",
  visitors: "¿Recibís visitas en casa?",
  sleepRoutine: "¿Cuál es tu rutina de sueño?",
  workRoutine: "¿Cuándo preferís estudiar/trabajar?",
  noCigarettes: "¿No aceptás fumadores?",
  noWeed: "¿No aceptás consumidores de marihuana?",
  petsPreference: "¿Preferencias sobre mascotas?",
  tidinessMin: "Nivel mínimo de limpieza",
  schedulePref: "Preferencia de horario",
  guestsMax: "Frecuencia máxima de invitados",
  musicMax: "Uso máximo de música/ruido",
  genderPref: "Preferencia de género",
  genders: "Géneros",
  gender: "Género",
  onlyWithPhoto: "¿Perfiles con foto?",
};
