import {
  Language,
  Interest,
  ZodiacSign,
  SmokesCigarettes,
  SmokesWeed,
  Alcohol,
  PetType,
  PetsOk,
  Tidiness,
  Schedule,
  GuestsFreq,
  MusicUsage,
  GenderPreference,
  Cooking,
  Diet,
  SharePolicy,
} from "../enums/searchPreferences.enums";

const zodiacOptions = [
  { value: ZodiacSign.ARIES, label: "Aries" },
  { value: ZodiacSign.TAURUS, label: "Tauro" },
  { value: ZodiacSign.GEMINI, label: "Géminis" },
  { value: ZodiacSign.CANCER, label: "Cáncer" },
  { value: ZodiacSign.LEO, label: "Leo" },
  { value: ZodiacSign.VIRGO, label: "Virgo" },
  { value: ZodiacSign.LIBRA, label: "Libra" },
  { value: ZodiacSign.SCORPIO, label: "Escorpio" },
  { value: ZodiacSign.SAGITTARIUS, label: "Sagitario" },
  { value: ZodiacSign.CAPRICORN, label: "Capricornio" },
  { value: ZodiacSign.AQUARIUS, label: "Acuario" },
  { value: ZodiacSign.PISCES, label: "Piscis" },
];

const interestOptions = [
  { value: Interest.GAMING, label: "Videojuegos" },
  { value: Interest.READING, label: "Lectura" },
  { value: Interest.COOKING, label: "Cocina" },
  { value: Interest.SPORTS, label: "Deportes" },
  { value: Interest.MUSIC, label: "Música" },
  { value: Interest.TRAVEL, label: "Viajes" },
  { value: Interest.ART, label: "Arte" },
  { value: Interest.TECHNOLOGY, label: "Tecnología" },
  { value: Interest.FITNESS, label: "Fitness" },
  { value: Interest.PHOTOGRAPHY, label: "Fotografía" },
  { value: Interest.MOVIES, label: "Cine" },
  { value: Interest.DANCE, label: "Danza" },
  { value: Interest.OTHER, label: "Otro" },
];

export const QUESTION_OPTIONS = {
  smoking: [
    { value: SmokesCigarettes.NO, label: "No fumo" },
    { value: SmokesCigarettes.REGULAR, label: "Fumo" },
    { value: SmokesCigarettes.SOCIALLY, label: "Fumador social" },
  ],
  marijuana: [
    { value: SmokesWeed.NO, label: "No fumo" },
    { value: SmokesWeed.REGULAR, label: "Fumo" },
    { value: SmokesWeed.SOCIALLY, label: "Fumador social" },
  ],
  alcohol: [
    { value: Alcohol.NO, label: "No tomo" },
    { value: Alcohol.SOCIALLY, label: "Solo en eventos" },
    { value: Alcohol.REGULAR, label: "Regularmente" },
  ],
  pets: [
    { value: PetType.DOG, label: "Perro" },
    { value: PetType.CAT, label: "Gato" },
    { value: PetType.OTHER, label: "Otro" },
    { value: "none", label: "No tengo" },
  ],
  petsOwned: [
    { value: PetType.DOG, label: "Perro" },
    { value: PetType.CAT, label: "Gato" },
    { value: PetType.OTHER, label: "Otro" },
  ],
  acceptPets: [
    { value: PetsOk.CATS_DOGS_OK, label: "Sí, me gustan" },
    { value: PetsOk.CATS_OK, label: "Solo gatos" },
    { value: PetsOk.DOGS_OK, label: "Solo perros" },
    { value: PetsOk.NO, label: "No acepto" },
  ],
  tidiness: [
    { value: Tidiness.NEAT, label: "Muy ordenado" },
    { value: Tidiness.AVERAGE, label: "Algo ordenado" },
    { value: Tidiness.CHILL, label: "Poco ordenado" },
  ],
  visitors: [
    { value: GuestsFreq.WEEKLY_PLUS, label: "Recibo muchas visitas" },
    { value: GuestsFreq.SOMETIMES, label: "Recibo visitas a veces" },
    { value: GuestsFreq.RARELY, label: "Raramente recibo visitas" },
  ],
  sleepRoutine: [
    { value: Schedule.EARLY_BIRD, label: "Madrugador" },
    { value: Schedule.NIGHT_OWL, label: "Nocturno" },
    { value: Schedule.MIXED, label: "Flexible" },
  ],
  cooking: [
    { value: Cooking.RARE, label: "Raramente cocino" },
    { value: Cooking.SOMETIMES, label: "A veces cocino" },
    { value: Cooking.OFTEN, label: "Cocino seguido" },
  ],
  diet: [
    { value: Diet.NONE, label: "Sin restricciones" },
    { value: Diet.VEGETARIAN, label: "Vegetariano" },
    { value: Diet.VEGAN, label: "Vegano" },
    { value: Diet.OTHER, label: "Otra" },
  ],
  sharePolicy: [
    { value: SharePolicy.STRICT, label: "Cada uno lo suyo" },
    { value: SharePolicy.ASK_FIRST, label: "Preguntar primero" },
    { value: SharePolicy.BASIC_SHARED, label: "Compartir básicos" },
  ],
  interests: interestOptions,
  zodiacSign: zodiacOptions,
  noCigarettes: [
    { value: "false", label: "Sí acepto" },
    { value: "true", label: "No acepto" },
  ],
  noWeed: [
    { value: "false", label: "Sí acepto" },
    { value: "true", label: "No acepto" },
  ],
  petsPreference: [
    { value: "noPets", label: "No mascotas" },
    { value: "petsRequired", label: "Con mascotas" },
    { value: "none", label: "Sin preferencia" },
  ],
  tidinessMin: [
    { value: Tidiness.CHILL, label: "Relajado" },
    { value: Tidiness.AVERAGE, label: "Promedio" },
    { value: Tidiness.NEAT, label: "Muy ordenado" },
  ],
  schedulePref: [
    { value: Schedule.EARLY_BIRD, label: "Madrugador (6am-10pm)" },
    { value: Schedule.MIXED, label: "Mixto (8am-12am)" },
    { value: Schedule.NIGHT_OWL, label: "Noctámbulo (12pm-3am)" },
  ],
  guestsMax: [
    { value: GuestsFreq.RARELY, label: "Rara vez" },
    { value: GuestsFreq.SOMETIMES, label: "A veces" },
    { value: GuestsFreq.WEEKLY_PLUS, label: "Semanalmente o más" },
  ],
  musicMax: [
    { value: MusicUsage.HEADPHONES, label: "Solo con audífonos" },
    { value: MusicUsage.SPEAKER_DAY, label: "Parlantes durante el día" },
    { value: MusicUsage.SPEAKER_FLEX, label: "Parlantes flexible" },
  ],
  genderPref: [
    { value: GenderPreference.ANY, label: "Cualquier género" },
    { value: GenderPreference.MALE, label: "Hombres" },
    { value: GenderPreference.FEMALE, label: "Mujeres" },
    { value: GenderPreference.NON_BINARY, label: "No binario" },
    { value: GenderPreference.UNSPECIFIED, label: "Sin especificar" },
    { value: GenderPreference.MOSTLY_MEN, label: "Mayormente hombres" },
    { value: GenderPreference.MOSTLY_WOMEN, label: "Mayormente mujeres" },
  ],
  genders: [
    { value: "MALE", label: "Hombres" },
    { value: "FEMALE", label: "Mujeres" },
    { value: "NON_BINARY", label: "No binario" },
    { value: "OTHER", label: "Otro" },
    { value: "MOSTLY_MEN", label: "Mayormente hombres" },
    { value: "MOSTLY_WOMEN", label: "Mayormente mujeres" },
  ],
  onlyWithPhoto: [
    { value: "true", label: "Solo con foto" },
    { value: "false", label: "Con o sin foto" },
  ],
  gender: [
    { value: "MALE", label: "Hombre" },
    { value: "FEMALE", label: "Mujer" },
    { value: "NON_BINARY", label: "No binario" },
    { value: "UNSPECIFIED", label: "Prefiero no decir" },
  ],
  languagesPref: [
    { value: Language.SPANISH, label: "Español" },
    { value: Language.ENGLISH, label: "Inglés" },
    { value: Language.PORTUGUESE, label: "Portugués" },
    { value: Language.FRENCH, label: "Francés" },
    { value: Language.ITALIAN, label: "Italiano" },
    { value: Language.GERMAN, label: "Alemán" },
  ],
  interestsPref: interestOptions,
  zodiacPref: zodiacOptions,
};
